<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="1" total="9" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="182983" started-at="2022-09-14T20:35:29Z" finished-at="2022-09-14T20:38:32Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="32767" started-at="2022-09-14T20:35:29Z" finished-at="2022-09-14T20:36:02Z">
      <class name="testCases.ValidLoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:testCases.ValidLoginPageTest@41e36e46]" name="setup" is-config="true" duration-ms="6166" started-at="2022-09-14T20:35:29Z" finished-at="2022-09-14T20:35:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="t1(java.lang.String, java.lang.String)[pri:1, instance:testCases.ValidLoginPageTest@41e36e46]" name="t1" duration-ms="19673" started-at="2022-09-14T20:35:38Z" data-provider="dataexcel" finished-at="2022-09-14T20:35:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr437157]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ajAruqu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method status="PASS" signature="t2()[pri:0, instance:testCases.ValidLoginPageTest@41e36e46]" name="t2" duration-ms="717" started-at="2022-09-14T20:35:57Z" depends-on-methods="testCases.ValidLoginPageTest.t1" finished-at="2022-09-14T20:35:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
        <test-method status="PASS" signature="t4()[pri:0, instance:testCases.ValidLoginPageTest@41e36e46]" name="t4" duration-ms="3280" started-at="2022-09-14T20:35:58Z" depends-on-methods="testCases.ValidLoginPageTest.t1" finished-at="2022-09-14T20:36:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="PASS" signature="exit()[pri:0, instance:testCases.ValidLoginPageTest@41e36e46]" name="exit" is-config="true" duration-ms="711" started-at="2022-09-14T20:36:01Z" finished-at="2022-09-14T20:36:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- testCases.ValidLoginPageTest -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="28101" started-at="2022-09-14T20:36:02Z" finished-at="2022-09-14T20:36:30Z">
      <class name="testCases.InvalidLoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:testCases.InvalidLoginPageTest@393671df]" name="setup" is-config="true" duration-ms="5417" started-at="2022-09-14T20:36:02Z" finished-at="2022-09-14T20:36:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="t1(java.lang.String, java.lang.String)[pri:5, instance:testCases.InvalidLoginPageTest@393671df]" name="t1" duration-ms="21843" started-at="2022-09-14T20:36:08Z" data-provider="dataexcel" finished-at="2022-09-14T20:36:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr371386]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[YhyrYvu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method status="PASS" signature="exit()[pri:0, instance:testCases.InvalidLoginPageTest@393671df]" name="exit" is-config="true" duration-ms="792" started-at="2022-09-14T20:36:29Z" finished-at="2022-09-14T20:36:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- testCases.InvalidLoginPageTest -->
    </test> <!-- Test2 -->
    <test name="Test3" duration-ms="28444" started-at="2022-09-14T20:36:30Z" finished-at="2022-09-14T20:36:59Z">
      <class name="testCases.HomePageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:testCases.HomePageTest@6973b51b]" name="setup" is-config="true" duration-ms="5679" started-at="2022-09-14T20:36:30Z" finished-at="2022-09-14T20:36:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="homeTitleTest(java.lang.String, java.lang.String)[pri:0, instance:testCases.HomePageTest@6973b51b]" name="homeTitleTest" duration-ms="21930" started-at="2022-09-14T20:36:36Z" data-provider="dataexcel" finished-at="2022-09-14T20:36:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr437157]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ajAruqu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homeTitleTest -->
        <test-method status="FAIL" signature="idTest()[pri:0, instance:testCases.HomePageTest@6973b51b]" name="idTest" duration-ms="55" started-at="2022-09-14T20:36:58Z" finished-at="2022-09-14T20:36:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Manger Id : mngr391197] but found [Manger Id : mngr437157]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Manger Id : mngr391197] but found [Manger Id : mngr437157]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.HomePageTest.idTest(HomePageTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- idTest -->
        <test-method status="PASS" signature="exit()[pri:0, instance:testCases.HomePageTest@6973b51b]" name="exit" is-config="true" duration-ms="718" started-at="2022-09-14T20:36:58Z" finished-at="2022-09-14T20:36:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- testCases.HomePageTest -->
    </test> <!-- Test3 -->
    <test name="Test4" duration-ms="93632" started-at="2022-09-14T20:36:59Z" finished-at="2022-09-14T20:38:32Z">
      <class name="testCases.NewCustomerTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:testCases.NewCustomerTest@dbf57b3]" name="setup" is-config="true" duration-ms="27684" started-at="2022-09-14T20:36:59Z" finished-at="2022-09-14T20:37:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="addNewCustomerTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:testCases.NewCustomerTest@dbf57b3]" name="addNewCustomerTest" duration-ms="17307" started-at="2022-09-14T20:37:26Z" data-provider="dataexcel" finished-at="2022-09-14T20:37:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[manojkumaraa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[281992]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[shikarpur]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[shikarpur]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[UP]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[202395]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[9599]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[manoj111@gmail.com]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[789585]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.UnhandledAlertException">
            <message>
              <![CDATA[unexpected alert open: {Alert text : Customer could not be added !!}
  (Session info: chrome=105.0.5195.127): Customer could not be added !!
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-PPS', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 105.0.5195.127, chrome: {chromedriverVersion: 105.0.5195.52 (412c95e51883..., userDataDir: C:\Users\manoj\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:63824}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c250648b68a2f72475e749af6962ffa2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Customer could not be added !!}
  (Session info: chrome=105.0.5195.127): Customer could not be added !!
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-PPS', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 105.0.5195.127, chrome: {chromedriverVersion: 105.0.5195.52 (412c95e51883..., userDataDir: C:\Users\manoj\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:63824}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c250648b68a2f72475e749af6962ffa2
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:922)
at pages.NewCustomer.addNewCustomer(NewCustomer.java:85)
at testCases.NewCustomerTest.addNewCustomerTest(NewCustomerTest.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.UnhandledAlertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomerTest -->
        <test-method status="PASS" signature="exit()[pri:0, instance:testCases.NewCustomerTest@dbf57b3]" name="exit" is-config="true" duration-ms="761" started-at="2022-09-14T20:37:44Z" finished-at="2022-09-14T20:37:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method status="PASS" signature="setup()[pri:0, instance:testCases.NewCustomerTest@dbf57b3]" name="setup" is-config="true" duration-ms="27422" started-at="2022-09-14T20:37:45Z" finished-at="2022-09-14T20:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="addNewCustomerTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:testCases.NewCustomerTest@dbf57b3]" name="addNewCustomerTest" duration-ms="17380" started-at="2022-09-14T20:38:12Z" data-provider="dataexcel" finished-at="2022-09-14T20:38:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[manojkumarbb]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[281992]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[shikarpur]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[shikarpur]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[UP]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[202395]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[9599]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[manoj222@gmail.com]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[789585]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.UnhandledAlertException">
            <message>
              <![CDATA[unexpected alert open: {Alert text : Customer could not be added !!}
  (Session info: chrome=105.0.5195.127): Customer could not be added !!
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-PPS', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 105.0.5195.127, chrome: {chromedriverVersion: 105.0.5195.52 (412c95e51883..., userDataDir: C:\Users\manoj\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:63904}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: ee141e5b3a7cecd28a3ff605b10d5d48]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Customer could not be added !!}
  (Session info: chrome=105.0.5195.127): Customer could not be added !!
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-PPS', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 105.0.5195.127, chrome: {chromedriverVersion: 105.0.5195.52 (412c95e51883..., userDataDir: C:\Users\manoj\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:63904}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: ee141e5b3a7cecd28a3ff605b10d5d48
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:922)
at pages.NewCustomer.addNewCustomer(NewCustomer.java:85)
at testCases.NewCustomerTest.addNewCustomerTest(NewCustomerTest.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.UnhandledAlertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomerTest -->
        <test-method status="PASS" signature="exit()[pri:0, instance:testCases.NewCustomerTest@dbf57b3]" name="exit" is-config="true" duration-ms="3037" started-at="2022-09-14T20:38:29Z" finished-at="2022-09-14T20:38:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- testCases.NewCustomerTest -->
    </test> <!-- Test4 -->
  </suite> <!-- Suite -->
</testng-results>
